### ISSUE TITLE
promu failing to produce static binaries

### ISSUE THREAD

**Issue by Gouthamve** [prometheus/promu#60]
Compiling Prometheus via promu produces a dynamic build. But using `CGO_ENABLED=0` env var produces a static one.

promu should natively produce a static binary.

Ref: prometheus/prometheus#2460

**Comment by mxinden** [comment]
Adding `CGO_ENABLED=0` to `promu build` would force every user to have write access to `$GOROOT` because go will try to rebuild all the standard lib packages and write them back to `$GOROOT` (See [comment](https://github.com/golang/go/issues/18981#issuecomment-278070252)). 

Instead we could run the standard `build` command in a docker container. But this would require every user to have docker installed.

If you need a static binary I suggest you run `promu crossbuild` (See the promu [README](https://github.com/prometheus/promu/blob/master/README.md)). Make sure you comment out all architectures you don't need in the `.promu.yml` file under `crossbuild`/`platforms`. You will find your static binary in `.build/<your-arch>/prometheus`.

**Comment by Gouthamve** [comment]
Yep, while I did not know about the side-effects of using `CGO_ENABLED=0`, I donot want to use that.

The goal here is that `promu build` itself should build a static binary like the `promu crossbuild` command. The help also seems to suggest that promu builds static ones:
```
Usage:
  promu build [flags]

Flags:
      --cgo             Enable CGO
      --prefix string   Specific dir to store binaries (default is .)

Global Flags:
      --config string   Config file (default is ./.promu.yml)
  -v, --verbose         Verbose output
      --viper           Use Viper for configuration (default true)
```

I also ran `promu build --cgo=false` and even that is giving dynamic binary :(

**Comment by sdurrheimer** [comment]
This is because when we use `--cgo=false` (which is the default), we don't set `CGO_ENABLED=0` explicitely [here](https://github.com/prometheus/promu/blob/master/cmd/build.go#L91-L94).

Even he we don't specify `CGO_ENABLED=1` explicitely, `Golang` might use some CGO.

**Comment by Gouthamve** [comment]
Umm, wait. Let me backup a little here.
So, promu by default produces binaries depending on the env_var, but we can explicitly ask it to use CGO.

Don't you think static binaries should be the default?
Or enable a way to make it build static binaries irrespective of the env_var?

**Comment by sdurrheimer** [comment]
By default, `promu build` try to act like a `go build` command as transparent as possible. So to build a project statically, you need to specify correct [`goflags`](https://github.com/prometheus/promu/blob/master/doc/examples/.promu.yml#L14) and the [`cgo`](https://github.com/prometheus/promu/blob/master/doc/examples/.promu.yml#L4) config.

However in some cases, we forces some [`envvars`](https://github.com/prometheus/promu/blob/master/cmd/build.go#L90-L94) or [`goflags`](https://github.com/prometheus/promu/blob/master/cmd/build.go#L145-L154) to fix some issues or to help produce static binaries.

**Comment by discordianfish** [comment]
@sdurrheimer I'm confused.. So what's the right way to enable static builds? It seems like there are scenarios where not setting CGO_ENABLED will make it build dynamically linked while setting CGO_ENABLED=0 explicitly gives you a statically linked binary. Even if  `-a -tags netgo` flags are used.

**Comment by sdurrheimer** [comment]
Unfortunately, this is the current golang behavior. It depends on the project's code. I don't know how to force golang to build statically besides setting `CGO_ENABLED=0` explicitly.
